# Generated by Django 4.2.23 on 2025-06-28 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wardrobe.clothingcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ai_analysis_status', models.CharField(choices=[('pending', 'Pending Analysis'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Analysis Failed')], default='pending', max_length=20)),
                ('wear_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wardrobe.clothingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('image_type', models.CharField(choices=[('main', 'Main Image'), ('tag', 'Price Tag'), ('detail', 'Detail Shot'), ('back', 'Back View'), ('side', 'Side View')], default='main', max_length=20)),
                ('upload_order', models.PositiveSmallIntegerField()),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wardrobe.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gemini_raw_response', models.JSONField()),
                ('extracted_data', models.JSONField()),
                ('confidence_scores', models.JSONField()),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('api_cost', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothing_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='wardrobe.clothingitem')),
            ],
        ),
    ]
